# fly.toml app configuration file generated for morning-snow-8667 on 2023-05-03T07:09:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-snow-8667"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
